# Generated by Django 5.2.3 on 2026-04-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cliente_telefono_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='puntos_acumulados',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registroconsumo',
            name='puntos_otorgados',
            field=models.DecimalField(decimal_places=2, help_text='Puntos otorgados por esta transacción', max_digits=10),
        ),
    ]
