# Generated by Django 5.2.3 on 2026-04-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cliente_puntos_acumulados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroconsumo',
            name='nro_boleta',
            field=models.CharField(blank=True, help_text='Número de boleta o factura emitida', max_length=50, null=True),
        ),
    ]
