# Generated by Django 5.2.3 on 2026-04-25 01:02 (modified manually)

from django.db import migrations, models


def rellenar_boletas_vacias(apps, schema_editor):
    """Asigna un nro_boleta temporal único a los registros que no tienen uno."""
    RegistroConsumo = apps.get_model('api', 'RegistroConsumo')
    registros_sin_boleta = RegistroConsumo.objects.filter(
        nro_boleta__isnull=True
    ) | RegistroConsumo.objects.filter(nro_boleta='')

    for reg in registros_sin_boleta:
        reg.nro_boleta = f'MIGRADO-{reg.id}'
        reg.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_nro_boleta_to_registro_consumo'),
    ]

    operations = [
        # Primero: rellenar vacíos con valores únicos temporales
        migrations.RunPython(rellenar_boletas_vacias, migrations.RunPython.noop),
        # Luego: aplicar unique=True
        migrations.AlterField(
            model_name='registroconsumo',
            name='nro_boleta',
            field=models.CharField(
                help_text='Número de boleta o factura emitida (único por registro)',
                max_length=50,
                unique=True,
                default='',
            ),
            preserve_default=False,
        ),
    ]
