# Generated by Django 5.2.3 on 2026-05-01 05:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_nro_boleta_unique_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCanjeable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('puntos_requeridos', models.IntegerField(help_text='Puntos necesarios para canjear este producto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('categoria', models.CharField(blank=True, default='General', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Producto Canjeable',
                'verbose_name_plural': 'Productos Canjeables',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
