# Generated by Django 5.2.3 on 2026-05-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_productocanjeable'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocanjeable',
            name='stock',
            field=models.IntegerField(default=0, help_text='Unidades disponibles en stock'),
        ),
    ]
