# Generated by Django 5.2.3 on 2026-05-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_stock_to_productocanjeable'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocanjeable',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Aparece en productos destacados del inicio'),
        ),
    ]
