# Generated by Django 5.2.3 on 2026-05-05 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_destacado_to_productocanjeable'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroconsumo',
            name='producto_canjeado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canjes_realizados', to='api.productocanjeable'),
        ),
    ]
