# Generated by Django 5.2.3 on 2026-05-05 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_registroconsumo_producto_canjeado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productocanjeable',
            name='categoria',
        ),
    ]
