# Generated by Django 5.2.3 on 2026-05-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_productocanjeable_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocombustible',
            name='puntos_por_diez_soles',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Puntos que otorga por cada 10 soles consumidos', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tipocombustible',
            name='puntos_por_galon',
            field=models.IntegerField(default=0, help_text='Puntos que otorga por cada galón consumido'),
        ),
    ]
