# Generated by Django 5.2.3 on 2026-05-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_tipocombustible_puntos_por_diez_soles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroconsumo',
            name='nro_boleta',
            field=models.CharField(blank=True, help_text='Número de boleta o factura emitida (único por registro)', max_length=50, null=True, unique=True),
        ),
    ]
