# Generated by Django 5.2.3 on 2026-05-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_registroconsumo_nro_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sucursal',
            field=models.CharField(blank=True, choices=[('Huánuco', 'Huánuco'), ('Huachipa', 'Huachipa')], max_length=50, null=True),
        ),
    ]
