# Generated by Django 5.2.3 on 2026-05-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_usuario_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroconsumo',
            name='nro_boleta',
            field=models.CharField(blank=True, help_text='Número de boleta o factura emitida (único por sucursal)', max_length=50, null=True),
        ),
    ]
